### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by PiotrWeppo** [PiotrWeppo/Scenes_Information_Recorder#1]
**File processing tasks:**
- [x] Searching for video files in a folder
- [x] Selecting a specific video file
- [x] Selecting where to start the video
- [x] Creating an Excel file and filling it with data

**Image processing tasks:**
- [x] Finding scene borders in a video.
- [x] Checking which scenes contain text throughout their duration
- [x] Image processing for higher precision OCR
- [ ]  

**Text recognition tasks:**
- [x] Reading text in video with OCR.
- [x] An algorithm for finding subtitles that can appear at any time, not just throughout the length of a clip

**Other tasks:**
- [x] Collecting realtime TC for each frame (from the beginning of the video).
- [x] Progress bar in CLI
- [ ] Speed optimization (using thread or multiprocessing)
- [x] Writing tests
